apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-kpp6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-kpp6
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-kpp6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-kpp6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-kpp6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-imib-tenant/status-quarkus-io/statusquarkusio-kpp6@sha256:2f1b4ebe48469772c297a4e3cf6cdc61f97ef032715176fc934d4829ec470ee7
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
